export const de = {
  brand: {
    name: "Ovara",
    logo: "OVARA",
    claim: "Building what’s next.",
    domain: "ovara.de",
    email: "homann@ovara.de",
  },
  nav: [
    ["Leistungen", "/leistungen"],
    ["Projekte", "/projekte"],
    ["Produkte", "/produkte"],
    ["Über Ovara", "/ueber-uns"],
    ["Kontakt", "/kontakt"],
  ],
  global: {
    projectCta: "Projekt starten",
    selectedWorkCta: "Projekt ansehen →",
    contactCta: "Projekt besprechen →",
  },
  home: {
    eyebrow: "TECHNOLOGY · SOFTWARE · AI · DIGITAL PRODUCTS",
    title: "Wir bauen digitale Produkte für das, was als Nächstes kommt.",
    intro:
      "Ovara entwickelt moderne Websites, Software, KI-Lösungen und digitale Produkte für Unternehmen — mit Design, Engineering und skalierbarer Technologie aus einer Hand.",
    primaryCta: "Projekt starten",
    secondaryCta: "Unsere Arbeit",
    focusAreas: ["Software", "AI", "Digital Products", "Web"],
    statementLabel: "OVARA",
    statementPrefix: "Technology built for",
    statementEmphasis: "what’s next.",
    buildEyebrow: "01 / WHAT WE BUILD",
    buildTitle: "Was wir bauen",
    buildIntro:
      "Von digitalen Auftritten bis zu produktionsreifen Softwareprodukten. Ovara verbindet Produktdenken, Design und Engineering.",
    workEyebrow: "02 / SELECTED WORK",
    workTitle: "Ausgewählte Arbeit",
    workIntro: "Nur reale Projekte. Keine Demo-Kunden, keine erfundenen Kennzahlen.",
    productsEyebrow: "03 / OVARA PRODUCTS",
    productsTitle: "Built by Ovara",
    productsIntro: "Eigene Produkte werden nur gezeigt, wenn sie real und öffentlich präsentierbar sind.",
    productsCta: "Alle Produkte ansehen →",
    capabilitiesEyebrow: "04 / CAPABILITIES",
    capabilitiesTitle: "Capabilities",
    capabilitiesIntro: "Breite technische Kompetenz, bewusst fokussiert eingesetzt.",
    technologyEyebrow: "05 / TECHNOLOGY",
    technologyTitle: "Technology",
    technologyIntro:
      "Technologie wird nach Produktanforderung gewählt — nicht nach Trend. Der Standard bleibt modern, typisiert und wartbar.",
    processEyebrow: "06 / PROCESS",
    processTitle: "Von Idee zu System",
    processIntro: "Ein klarer Produktprozess ohne Agenturtheater.",
    process: [
      ["01", "Discover", "Ziel, Nutzer, Anforderungen und reale technische Grenzen verstehen."],
      ["02", "Design", "Informationsarchitektur, Interface und Produkterlebnis präzise definieren."],
      ["03", "Build", "Saubere, typisierte und skalierbare Software produktionsreif umsetzen."],
      ["04", "Launch", "Testen, ausrollen, beobachten und ohne unnötige Reibung live bringen."],
      ["05", "Scale", "Auf Basis echter Nutzung iterieren, automatisieren und weiterentwickeln."],
    ],
    whyEyebrow: "07 / WHY OVARA",
    whyTitle: "Warum Ovara",
    whyIntro: "Der Unterschied liegt nicht in Claims, sondern in Entscheidungen während Design und Entwicklung.",
    why: [
      "Design und Engineering aus einem System",
      "Moderne Technologie statt Legacy-Stack",
      "AI-native Entwicklung, wo sie echten Nutzen schafft",
      "Skalierbare Architektur statt kurzfristiger Workarounds",
      "Schnelle Iterationen mit klaren Qualitäts-Gates",
      "Wartbare Systeme statt Abhängigkeit von Einzelpersonen",
    ],
    finalEyebrow: "START A PROJECT",
    finalTitle: "Lass uns etwas bauen, das bleibt.",
  },
} as const;
