export const en = {
  brand: {
    name: "Ovara",
    logo: "OVARA",
    claim: "Building what’s next.",
    domain: "ovara.de",
    email: "homann@ovara.de",
  },
  nav: [
    ["Services", "/services"],
    ["Projects", "/projects"],
    ["Products", "/products"],
    ["About Ovara", "/about"],
    ["Contact", "/contact"],
  ],
  global: {
    projectCta: "Start a project",
    selectedWorkCta: "View project →",
    contactCta: "Discuss a project →",
  },
  home: {
    eyebrow: "TECHNOLOGY · SOFTWARE · AI · DIGITAL PRODUCTS",
    title: "We build digital products for what comes next.",
    intro:
      "Ovara develops modern websites, software, AI solutions and digital products for companies — combining design, engineering and scalable technology.",
    primaryCta: "Start a project",
    secondaryCta: "Our work",
    focusAreas: ["Software", "AI", "Digital Products", "Web"],
    statementLabel: "OVARA",
    statementPrefix: "Technology built for",
    statementEmphasis: "what’s next.",
    buildEyebrow: "01 / WHAT WE BUILD",
    buildTitle: "What we build",
    buildIntro:
      "From high-end digital experiences to production-ready software products. Ovara combines product thinking, design and engineering.",
    workEyebrow: "02 / SELECTED WORK",
    workTitle: "Selected work",
    workIntro: "Real projects only. No demo clients and no invented metrics.",
    productsEyebrow: "03 / OVARA PRODUCTS",
    productsTitle: "Built by Ovara",
    productsIntro: "Own products are shown only when they are real and ready to be presented publicly.",
    productsCta: "View all products →",
    capabilitiesEyebrow: "04 / CAPABILITIES",
    capabilitiesTitle: "Capabilities",
    capabilitiesIntro: "Broad technical capability, applied with deliberate focus.",
    technologyEyebrow: "05 / TECHNOLOGY",
    technologyTitle: "Technology",
    technologyIntro:
      "Technology is chosen for the product requirement, not the trend. The baseline stays modern, typed and maintainable.",
    processEyebrow: "06 / PROCESS",
    processTitle: "From idea to system",
    processIntro: "A clear product process without agency theatre.",
    process: [
      ["01", "Discover", "Understand goals, users, requirements and real technical constraints."],
      ["02", "Design", "Define information architecture, interface and product experience precisely."],
      ["03", "Build", "Implement clean, typed and scalable software for production."],
      ["04", "Launch", "Test, deploy, observe and release without unnecessary friction."],
      ["05", "Scale", "Iterate, automate and evolve based on real usage."],
    ],
    whyEyebrow: "07 / WHY OVARA",
    whyTitle: "Why Ovara",
    whyIntro: "The difference is not in claims, but in the decisions made during design and engineering.",
    why: [
      "Design and engineering from one system",
      "Modern technology instead of legacy stacks",
      "AI-native development where it creates real value",
      "Scalable architecture instead of short-term workarounds",
      "Fast iterations with clear quality gates",
      "Maintainable systems instead of dependence on individuals",
    ],
    finalEyebrow: "START A PROJECT",
    finalTitle: "Let’s build something that lasts.",
  },
} as const;
